using System.Reflection;
using System.Runtime.Loader;
using System.Text;

namespace Cli;

/// <summary>
/// NativeAOT can't create generic collections through reflection unless their code was generated ahead of time.
/// This lists every List, HashSet and Dictionary used by a field or property in the given assemblies as an
/// rd.xml directive, so the YAML serializer can create them. hosts/Directory.Build.targets runs it before ILC.
/// </summary>
sealed class YamlAotDirectivesCommand : ICommand
{
    static readonly Type[] collectionDefinitions = [typeof( List<> ), typeof( HashSet<> ), typeof( Dictionary<,> )];

    public string Name => "yaml aot-directives";

    public string Summary => "Write NativeAOT rd.xml directives for the collections YAML may create.";

    public string Usage => "yaml aot-directives --out <rd.xml> <assembly.dll>...";

    public int Run ( string[] args )
    {
        var arguments = new Arguments( args, valueOptions: ["out"], flags: [] );
        string output = arguments.Value( "out" ) ?? throw new UsageException( "--out is required." );
        if ( arguments.Positional.Count == 0 )
            throw new UsageException( "Give at least one assembly." );

        var context = new AssemblyLoadContext( "yaml-aot-directives", isCollectible: true );
        var directories = arguments.Positional.Select( path => Path.GetDirectoryName( Path.GetFullPath( path ) )! ).Distinct().ToList();
        context.Resolving += ( loadContext, name ) =>
        {
            var candidate = directories.Select( directory => Path.Combine( directory, name.Name + ".dll" ) ).FirstOrDefault( File.Exists );
            return candidate == null ? null : loadContext.LoadFromAssemblyPath( candidate );
        };

        var collections = new HashSet< Type >();
        var visited = new HashSet< Type >();
        foreach ( string path in arguments.Positional )
        {
            var assembly = context.LoadFromAssemblyPath( Path.GetFullPath( path ) );
            foreach ( var type in LoadableTypes( assembly ) )
            {
                const BindingFlags MEMBERS = BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly;
                foreach ( var field in type.GetFields( MEMBERS ) )
                    Visit( field.FieldType, collections, visited );

                foreach ( var property in type.GetProperties( MEMBERS ) )
                    Visit( property.PropertyType, collections, visited );
            }
        }

        string xml = Format( collections );
        bool unchanged = File.Exists( output ) && File.ReadAllText( output ) == xml;
        if ( !unchanged )
        {
            Directory.CreateDirectory( Path.GetDirectoryName( Path.GetFullPath( output ) )! );
            File.WriteAllText( output, xml );
        }

        Console.WriteLine( $"{collections.Count} collection types {( unchanged ? "unchanged in" : "written to" )} {output}" );
        return ExitCode.SUCCESS;
    }

    static void Visit ( Type type, HashSet< Type > collections, HashSet< Type > visited )
    {
        if ( type.ContainsGenericParameters || type.IsPointer || type.IsByRef || !visited.Add( type ) )
            return;

        if ( type.IsArray )
        {
            Visit( type.GetElementType()!, collections, visited );
            return;
        }

        if ( !type.IsGenericType )
            return;

        var definition = type.GetGenericTypeDefinition();
        if ( collectionDefinitions.Any( collection => collection.FullName == definition.FullName ) )
            collections.Add( type );

        foreach ( var argument in type.GetGenericArguments() )
            Visit( argument, collections, visited );
    }

    static string Format ( IEnumerable< Type > collections )
    {
        var builder = new StringBuilder();
        builder.AppendLine( "<!-- Generated by `cli yaml aot-directives`. -->" );
        builder.AppendLine( "<Directives xmlns=\"http://schemas.microsoft.com/netfx/2013/01/metadata\">" );
        builder.AppendLine( "  <Application>" );
        foreach ( var group in collections.GroupBy( type => type.Assembly.GetName().Name! ).OrderBy( group => group.Key, StringComparer.Ordinal ) )
        {
            builder.AppendLine( $"    <Assembly Name=\"{group.Key}\">" );
            foreach ( string name in group.Select( TypeName ).Order( StringComparer.Ordinal ) )
                builder.AppendLine( $"      <Type Name=\"{System.Security.SecurityElement.Escape( name )}\" Dynamic=\"Required All\" />" );

            builder.AppendLine( "    </Assembly>" );
        }

        builder.AppendLine( "  </Application>" );
        builder.AppendLine( "</Directives>" );
        return builder.ToString();
    }

    /// <summary>A type name with assembly-qualified generic arguments, e.g. <c>List`1[[Game.Point,Game]]</c>.</summary>
    static string TypeName ( Type type )
    {
        if ( type.IsArray )
            return TypeName( type.GetElementType()! ) + "[" + new string( ',', type.GetArrayRank() - 1 ) + "]";

        if ( !type.IsGenericType )
            return type.FullName!;

        var arguments = type.GetGenericArguments().Select( argument => $"[{TypeName( argument )},{argument.Assembly.GetName().Name}]" );
        return type.GetGenericTypeDefinition().FullName + "[" + string.Join( ",", arguments ) + "]";
    }

    static IEnumerable< Type > LoadableTypes ( Assembly assembly )
    {
        try
        {
            return assembly.GetTypes();
        }
        catch ( ReflectionTypeLoadException exception )
        {
            return exception.Types.OfType< Type >();
        }
    }
}
